#!/bin/python

#Emma is playing a new mobile game that starts with consecutively numbered clouds. Some of the clouds are thunderheads and others are cumulus. She can jump on any cumulus cloud having a number that is equal to the number of the current cloud plus  or . She must avoid the thunderheads. Determine the minimum number of jumps it will take Emma to jump from her starting postion to the last cloud. It is always possible to win the game.

#For each game, Emma will get an array of clouds numbered  if they are safe or  if they must be avoided. For example,  indexed from . The number on each cloud is its index in the list so she must avoid the clouds at indexes  and . She could follow the following two paths:  or . The first path takes jumps while the second takes .

#Function Description

#Complete the jumpingOnClouds function in the editor below. It should return the minimum number of jumps required, as an integer.

#jumpingOnClouds has the following parameter(s):

#c: an array of binary integers
#Input Format

#The first line contains an integer , the total number of clouds. The second line contains  space-separated binary integers describing clouds  where .

#Constraints

#Output Format

#Print the minimum number of jumps needed to win the game.



import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c):
    
    
    jumps = 0
    current = 0
    for i in range(0,len(c)-2):
        
        print len(c)
        print current
        
        if current == len(c)-1:
            break
        
        if current < len(c)-2:
            if c[current+2] == 0:
                jumps += 1
                current += 2
                continue
                
            
        if c[current+1] == 0:    
            jumps += 1
            current += 1
            
    if len(c) == 2:
        if c[current+1] == 0:
            return 1
        
    return jumps

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input())

    c = map(int, raw_input().rstrip().split())

    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
